[
 {
  "author": "simonetripodi", 
  "date": "2011-06-24T16:42:49.784147Z", 
  "msg": [
   "improved error message"
  ], 
  "revision_id": "1139380"
 }, 
 {
  "author": "marvin", 
  "date": "2011-06-24T16:36:11.924429Z", 
  "msg": [
   "Reduce exposure of some symbols which had to be exposed during transition from", 
   "Perl to C."
  ], 
  "revision_id": "1139379"
 }, 
 {
  "author": "julianfoad", 
  "date": "2011-06-24T16:32:53.587411Z", 
  "msg": [
   "* subversion/tests/cmdline/commit_tests.py", 
   "(commit_url): Remove this test, as it's duplicated by invalid_wcpath_commit()", 
   "in input_validation_tests.py."
  ], 
  "revision_id": "1139378"
 }, 
 {
  "author": "sebb", 
  "date": "2011-06-24T16:32:43.428627Z", 
  "msg": [
   "Add ids (some not known)"
  ], 
  "revision_id": "1139377"
 }, 
 {
  "author": "mikem", 
  "date": "2011-06-24T16:32:30.568554Z", 
  "msg": [
   "DERBY-5284 A derby crash at exactly right time during a btree split can cause a", 
   "corrupt db which can not be booted.", 
   "backport fix #1139085 from 10.4 branch to 10.1 branch. clean merge by doing", 
   "merge of the 10.4 conflict resolved change.", 
   "Fixed a problem during BTREE split.  The first phase of btree split sees", 
   "if it can reclaim space from committed deleted rows.  If it finds any", 
   "it purges these rows in a nested internal transaction.  It needs to hold", 
   "the latch on the page until end of transaction, but did not.  This allowed", 
   "a very small window of a few instructions where another insert could use", 
   "the space on the page and then a system crash could cause the purges to undo", 
   "but fail due to the insert.", 
   "The fix was to hold the latch and let commit release it."
  ], 
  "revision_id": "1139376"
 }
]