[
 {
  "author": "hwright", 
  "date": "2011-08-05T17:14:24.974683Z", 
  "msg": [
   "On the fs-py branch:", 
   "Introduce an exception type which can be used to throw errors back to", 
   "Subversion from Python.", 
   "We put the exception type into a static variable in the python util layer,", 
   "where it will be useful for future checks.", 
   "* subversion/python/svn/__init__.py", 
   "(SubversionException): New.", 
   "* subversion/libsvn_fs_py/py_util.c", 
   "(p_exception_type): New.", 
   "(finalize_python): Release the exception type object.", 
   "(svn_fs_py__init_py): Attempt to grab the exception type."
  ], 
  "revision_id": "1154320"
 }, 
 {
  "author": "anathaniel", 
  "date": "2011-08-05T17:07:03.987033Z", 
  "msg": [
   "Limit scope of @SuppressWarnings(\"unchecked\")"
  ], 
  "revision_id": "1154319"
 }, 
 {
  "author": "anathaniel", 
  "date": "2011-08-05T17:05:58.867743Z", 
  "msg": [
   "Limit scope of @SuppressWarnings(\"unchecked\")"
  ], 
  "revision_id": "1154318"
 }, 
 {
  "author": "kwright", 
  "date": "2011-08-05T17:05:58.457617Z", 
  "msg": [
   "Remove merged branch"
  ], 
  "revision_id": "1154317"
 }, 
 {
  "author": "anathaniel", 
  "date": "2011-08-05T17:04:46.257425Z", 
  "msg": [
   "Limit scope of @SuppressWarnings(\"unchecked\")"
  ], 
  "revision_id": "1154316"
 }
]