[
 {
  "author": "slebresne", 
  "date": "2011-09-13T13:59:58.388709Z", 
  "msg": [
   "merge from 1.0.0"
  ], 
  "revision_id": "1170185"
 }, 
 {
  "author": "slebresne", 
  "date": "2011-09-13T13:58:41.452275Z", 
  "msg": [
   "minor cleanups related to reference counting"
  ], 
  "revision_id": "1170184"
 }, 
 {
  "author": "hwright", 
  "date": "2011-09-13T13:56:05.765840Z", 
  "msg": [
   "* tools/dist/release.py", 
   "(roll_tarballs): Early error if the deploy directory already exists."
  ], 
  "revision_id": "1170183"
 }, 
 {
  "author": "robbie", 
  "date": "2011-09-13T13:55:42.973730Z", 
  "msg": [
   "QPID-3448: catch exceptions from the underlying Transport/Session/Connection and rethrow as a JMSException like users are expecting", 
   "Applied patch by Oleksandr Rudyy <orudyy@gmail.com> and myself."
  ], 
  "revision_id": "1170182"
 }, 
 {
  "author": "roger", 
  "date": "2011-09-13T13:54:46.260056Z", 
  "msg": [
   "fix spelling issue within license"
  ], 
  "revision_id": "1170181"
 }
]