[
 {
  "author": "dirkv", 
  "date": "2003-08-11T14:49:33.000000Z", 
  "msg": [
   "No need to throw DbcpException the interface allows a checked Exception"
  ], 
  "revision_id": "131979"
 }, 
 {
  "author": "dirkv", 
  "date": "2003-08-11T14:47:31.000000Z", 
  "msg": [
   "Bugzilla Bug 21229", 
   "ConnectionFactory throws SQLException but implementations don't", 
   "Deprecated DbcpException in favor of checked SQLException", 
   "as suggested by Brian Campbell"
  ], 
  "revision_id": "131978"
 }, 
 {
  "author": "dirkv", 
  "date": "2003-08-11T14:37:12.000000Z", 
  "msg": [
   "Bugzilla Bug 21418", 
   "Example code", 
   "Added Class.forName to the examples as suggested by David Badia"
  ], 
  "revision_id": "131977"
 }, 
 {
  "author": "dirkv", 
  "date": "2003-08-11T14:08:39.000000Z", 
  "msg": [
   "Bugzilla Bug 18905", 
   "Couldn't get connection (Jdbc2PoolDataSource)", 
   "Jdbc2PoolDataSource.registerPool didn't check if the supplied username/password was correct.", 
   "A broken pool was registered and the next call to getConnection always used this pool.", 
   "Now registerPool tries to connect and returns the SQLException if it fails.", 
   "(this fix solved the 3 testcases that were failing for me)"
  ], 
  "revision_id": "131976"
 }, 
 {
  "author": "dirkv", 
  "date": "2003-08-11T12:21:47.000000Z", 
  "msg": [
   "Bugzilla Bug 19374", 
   "Potential for DelegateStatement, DelegateResultSet to be left open"
  ], 
  "revision_id": "131975"
 }
]