[
 {
  "author": "dirkv", 
  "date": "2003-08-11T16:02:10.000000Z", 
  "msg": [
   "use SQLNestedException for improved error messages"
  ], 
  "revision_id": "131984"
 }, 
 {
  "author": "dirkv", 
  "date": "2003-08-11T15:59:16.000000Z", 
  "msg": [
   "change to public class"
  ], 
  "revision_id": "131983"
 }, 
 {
  "author": "dirkv", 
  "date": "2003-08-11T15:02:07.000000Z", 
  "msg": [
   "Bugzilla Bug 21748:  BasicDataSource.close() throws NPE", 
   "If a BasicDataSource is closed without having been used, the connectionPool", 
   "will not have been initialised and a NPE will be thrown.", 
   "(Reported by Aaron Knauf)"
  ], 
  "revision_id": "131982"
 }, 
 {
  "author": "dirkv", 
  "date": "2003-08-11T14:53:34.000000Z", 
  "msg": [
   "Use SQLNestedException to report errors"
  ], 
  "revision_id": "131981"
 }, 
 {
  "author": "dirkv", 
  "date": "2003-08-11T14:51:25.000000Z", 
  "msg": [
   "A SQLException subclass containing another Throwable"
  ], 
  "revision_id": "131980"
 }
]