[
 {
  "author": "elecharny", 
  "date": "2005-03-27T18:42:07.680404Z", 
  "msg": [
   "A first working version of the new ASN.1 LDAP decoder."
  ], 
  "revision_id": "159169"
 }, 
 {
  "author": "elecharny", 
  "date": "2005-03-27T18:41:50.555816Z", 
  "msg": [
   "A first working version of the new ASN.1 LDAP decoder."
  ], 
  "revision_id": "159168"
 }, 
 {
  "author": "leosimons", 
  "date": "2005-03-27T18:41:35.462452Z", 
  "msg": [
   "I have no idea where this bug was re-introduced (maybe it has to do with a different pmock or python version, I dunno), but the name verify() on the verifier object clashes with the verify() that pmock uses itself. This meant that I had to replace the mock_verifier that pmock supplied with a custom class that did the same thing. However, I managed to only half-remove the original pmock-based verify-the-verifier line and that resulted in a failing testcase."
  ], 
  "revision_id": "159167"
 }, 
 {
  "author": "elecharny", 
  "date": "2005-03-27T18:41:32.978111Z", 
  "msg": [], 
  "revision_id": "159166"
 }, 
 {
  "author": "elecharny", 
  "date": "2005-03-27T18:41:18.447712Z", 
  "msg": [
   "A first working version of the new ASN.1 LDAP decoder."
  ], 
  "revision_id": "159165"
 }
]