[
 {
  "author": "pburba", 
  "date": "2007-11-28T17:07:51.608184Z", 
  "msg": [
   "New XFail test for reopened issue #2877", 
   "* subversion/tests/cmdline/merge_tests.py", 
   "(merge_source_normalization_and_subtree_merges):", 
   "(test_list): Add merge_source_normalization_and_subtree_merges and set", 
   "as XFail."
  ], 
  "revision_id": "868190"
 }, 
 {
  "author": "kameshj", 
  "date": "2007-11-28T12:58:46.892242Z", 
  "msg": [
   "Follow-up to r27982.", 
   "Fix doc string of 'get_parent_target_path_having_mergeinfo'.", 
   "* subversion/libsvn_fs_util/mergeinfo-sqlite-index.c", 
   "(get_parent_target_path_having_mergeinfo): Fix doc string", 
   "to follow the internal style of ALL CAPS parameter names. Document", 
   "the pool parameter.", 
   "Found by: kfogel"
  ], 
  "revision_id": "868189"
 }, 
 {
  "author": "kameshj", 
  "date": "2007-11-28T12:47:35.217145Z", 
  "msg": [
   "Follow-up to r27982.", 
   "Remove duplicate doc strings from source code in favour of the ones in", 
   "the header file.", 
   "* subversion/libsvn_fs_util/mergeinfo-sqlite-index.c", 
   "(svn_fs_mergeinfo__update_index,", 
   "svn_fs_mergeinfo__get_mergeinfo,", 
   "svn_fs_mergeinfo__get_commit_revs_for_merge_ranges): Remove doc string.", 
   "Found by: kfogel"
  ], 
  "revision_id": "868188"
 }, 
 {
  "author": "kameshj", 
  "date": "2007-11-28T12:10:45.066157Z", 
  "msg": [
   "Fix issue #3032 \"merge from a renamed branch fails while avoiding", 
   "repeat merges from renamed path\".", 
   "* subversion/libsvn_client/merge.c", 
   "(do_directory_merge): Resolve urls as they are named at start_rev and end_rev", 
   "by using merge_b->url at a peg revision of revision2. Use these resolved urls", 
   "to drive a merge report.", 
   "* subversion/tests/cmdline/merge_tests.py", 
   "(test_list): Remove XFail marker from", 
   "merge_from_renamed_branch_fails_while_avoiding_repeat_merge.", 
   "NOTE: This fix was reworked for efficiency in r28119."
  ], 
  "revision_id": "868187"
 }, 
 {
  "author": "kameshj", 
  "date": "2007-11-28T10:52:33.848785Z", 
  "msg": [
   "XFail Test for issue #3032 \"merge from a renamed branch fails while avoiding", 
   "repeat merges from renamed path\".", 
   "* subversion/tests/cmdline/merge_tests.py", 
   "(merge_from_renamed_branch_fails_while_avoiding_repeat_merge): New function.", 
   "(test_list): Add the above test as XFail test."
  ], 
  "revision_id": "868186"
 }
]