[
 {
  "author": "kfogel", 
  "date": "2008-01-09T02:00:15.721373Z", 
  "msg": [
   "On the reintegrate branch:", 
   "* subversion/tests/cmdline/merge_tests.py", 
   "(reintegrate_fail_on_stale_source): New test.", 
   "(test_list): Run it XFail."
  ], 
  "revision_id": "868890"
 }, 
 {
  "author": "kfogel", 
  "date": "2008-01-09T01:57:26.867240Z", 
  "msg": [
   "On the reintegrate branch:", 
   "* subversion/libsvn_client/merge.c", 
   "(svn_client_merge_reintegrate): Comment out debugging print statements."
  ], 
  "revision_id": "868889"
 }, 
 {
  "author": "epg", 
  "date": "2008-01-09T01:01:15.528300Z", 
  "msg": [
   "* subversion/mod_dav_svn/util.c", 
   "(dav_svn__operational_log): Follow-up to r28550: URI-escape", 
   "SVN-REPOS and SVN-REPOS-NAME values."
  ], 
  "revision_id": "868888"
 }, 
 {
  "author": "kfogel", 
  "date": "2008-01-08T22:36:38.493776Z", 
  "msg": [
   "* subversion/tests/cmdline/merge_tests.py", 
   "(reintegrate_fail_on_modified_wc, reintegrate_fail_on_mixed_rev_wc,", 
   "reintegrate_fail_on_switched_wc, reintegrate_fail_on_shallow_wc): New tests.", 
   "(test_list): Run them.", 
   "* reintegrate-branch-TODO: Note further test development."
  ], 
  "revision_id": "868887"
 }, 
 {
  "author": "pburba", 
  "date": "2008-01-08T21:43:41.513098Z", 
  "msg": [
   "Follow-up to r28791, fix another screw up...", 
   "* subversion/tests/cmdline/merge_tests.py", 
   "(mergeinfo_inheritance): Remove test coverage for issue #3067 added to this", 
   "test.  That was just some development work never intended to be committed.", 
   "The \"real\" test is 'new_subtrees_should_not_break_merge'."
  ], 
  "revision_id": "868886"
 }
]