[
 {
  "author": "sunny256", 
  "date": "2008-09-24T16:35:04.737220Z", 
  "msg": [
   "* subversion/po/nb.po: Typo fix."
  ], 
  "revision_id": "873340"
 }, 
 {
  "author": "blair", 
  "date": "2008-09-24T15:43:12.099692Z", 
  "msg": [
   "Allow a file external to be placed into a directory external which", 
   "doesn't already have an access baton for it.", 
   "* subversion/include/svn_error_codes.h", 
   "(SVN_ERR_RA_REPOS_ROOT_URL_MISMATCH):", 
   "New error code.  I put this in SVN_ERR_RA to match the", 
   "SVN_ERR_RA_UUID_MISMATCH error.", 
   "* subversion/libsvn_client/externals.c", 
   "(switch_file_external):", 
   "If svn_wc_adm_retrieve() cannot get an access baton, then try to", 
   "get an access baton using svn_wc_adm_open3() and if it succeeds,", 
   "check that the repos root URL for the file external matches the", 
   "repos root URL for the working copy the external is being placed", 
   "into.", 
   "Use target_adm_access instead of adm_access throughout the rest of", 
   "the function.", 
   "* subversion/tests/cmdline/externals_tests.py", 
   "(can_place_file_external_into_dir_external):", 
   "New unit test to check that a file external can be placed into a", 
   "directory external from the same repository but not a different", 
   "repository.", 
   "(test_list):", 
   "Add can_place_file_external_into_dir_external."
  ], 
  "revision_id": "873339"
 }, 
 {
  "author": "blair", 
  "date": "2008-09-24T05:50:28.765788Z", 
  "msg": [
   "* subversion/libsvn_client/externals.c", 
   "(switch_file_external):", 
   "Move a svn_error_t * declaration into the scope it is used."
  ], 
  "revision_id": "873338"
 }, 
 {
  "author": "danielsh", 
  "date": "2008-09-24T05:37:11.599751Z", 
  "msg": [
   "* STATUS: Add r33212 to r33201, and vote for both."
  ], 
  "revision_id": "873337"
 }, 
 {
  "author": "hwright", 
  "date": "2008-09-23T22:43:00.295358Z", 
  "msg": [
   "On the fs-rep-sharing branch:", 
   "Bring up-to-date with trunk."
  ], 
  "revision_id": "873336"
 }
]