[
 {
  "author": "arfrever", 
  "date": "2008-11-29T16:31:28.938250Z", 
  "msg": [
   "Follow-up to r34399:", 
   "Support the 'password-stores' configuration option in", 
   "svn_auth_get_platform_specific_client_providers().", 
   "* subversion/include/svn_auth.h", 
   "(svn_auth_get_platform_specific_client_providers): Add 'config' argument.", 
   "(svn_auth_get_platform_specific_provider,", 
   "svn_auth_get_platform_specific_client_providers): Delete partially", 
   "misleading information from doc string.", 
   "* subversion/libsvn_subr/auth.c", 
   "(svn_auth_get_platform_specific_client_providers): Add 'config' argument.", 
   "Use the 'password-stores' configuration option from 'config' to determine", 
   "order of the platform-specific authentication providers.", 
   "* subversion/libsvn_subr/cmdline.c", 
   "(svn_cmdline_create_auth_baton): Update call to", 
   "svn_auth_get_platform_specific_client_providers().", 
   "* subversion/bindings/javahl/native/SVNClient.cpp", 
   "(SVNClient::getContext): Update call to", 
   "svn_auth_get_platform_specific_client_providers().", 
   "* subversion/tests/libsvn_subr/auth-test.c", 
   "(test_platform_specific_auth_providers): Update call to", 
   "svn_auth_get_platform_specific_client_providers()."
  ], 
  "revision_id": "874545"
 }, 
 {
  "author": "arfrever", 
  "date": "2008-11-29T02:06:15.202492Z", 
  "msg": [
   "* build/ac-macros/swig.m4", 
   "(SVN_FIND_SWIG): Allow SWIG 1.3.36."
  ], 
  "revision_id": "874544"
 }, 
 {
  "author": "arfrever", 
  "date": "2008-11-28T23:54:06.017316Z", 
  "msg": [
   "Follow-up to r34359:", 
   "* subversion/bindings/swig/python/tests/trac/test.py: Explicitly declare", 
   "UTF-8 encoding for compatibility with Python 2.", 
   "Found by: jwhitlock"
  ], 
  "revision_id": "874543"
 }, 
 {
  "author": "arfrever", 
  "date": "2008-11-28T22:27:13.455579Z", 
  "msg": [
   "Follow-up to r34465:", 
   "* build/generator/gen_win.py", 
   "(WinGeneratorBase.create_dll_target): Use dict.keys() instead of", 
   "dict.iterkeys() for compatibility with Python 3.", 
   "Fix 'RuntimeError: maximum recursion depth exceeded' in CSVN. The fix isn't", 
   "compatible with Python 3, because Python 3 doesn't contain UserDict module.", 
   "* subversion/bindings/ctypes-python/csvn/types.py", 
   "(Hash._keys): New.", 
   "(Hash.keys): Use Hash._keys().", 
   "(Hash.items): Renamed from ...", 
   "(Hash.iteritems): ... this."
  ], 
  "revision_id": "874542"
 }, 
 {
  "author": "hwright", 
  "date": "2008-11-28T22:12:21.918880Z", 
  "msg": [
   "* subversion/libsvn_fs_fs/fs_fs.c", 
   "(svn_fs_fs__rev_get_root): Whitespace fix."
  ], 
  "revision_id": "874541"
 }
]