[
 {
  "author": "cmpilato", 
  "date": "2009-01-09T19:32:00.368810Z", 
  "msg": [
   "On the 'issue-3148-dev' branch: Rework the way failed-externals", 
   "notification is done so that errors that happen before we official", 
   "start messing with the external working copy look a little different", 
   "than those that happen *while* processing the external working copy,", 
   "and to maximize the amount of useful error information we can print.", 
   "No, this still doesn't pass the test suite.", 
   "* subversion/svn/notify.c", 
   "(notify): In the 'svn_wc_notify_failed_external' case, manage the", 
   "nb->in_external flag appropriately, and print the detailed error", 
   "(possible with another line that describes which external working", 
   "copy had the problem).", 
   "* subversion/libsvn_client/externals.c", 
   "(handle_external_item_change_wrapper): Clear the external error here."
  ], 
  "revision_id": "875200"
 }, 
 {
  "author": "pburba", 
  "date": "2009-01-09T18:06:03.660215Z", 
  "msg": [
   "Add a test for issue #3354", 
   "* subversion/tests/cmdline/update_tests.py", 
   "(update_moves_and_modifies_an_edited_file): New test.", 
   "(test_list): Add update_moves_and_modifies_an_edited_file and set", 
   "as XFail."
  ], 
  "revision_id": "875199"
 }, 
 {
  "author": "cmpilato", 
  "date": "2009-01-09T17:05:29.216298Z", 
  "msg": [
   "On the issue-3148-dev branch:  Add a BRANCH-README file."
  ], 
  "revision_id": "875198"
 }, 
 {
  "author": "julianfoad", 
  "date": "2009-01-09T16:55:22.287996Z", 
  "msg": [
   "On the issue-3334-dirs branch: merge changes from trunk up to r35115."
  ], 
  "revision_id": "875197"
 }, 
 {
  "author": "hwright", 
  "date": "2009-01-09T16:33:57.343835Z", 
  "msg": [
   "* subversion/libsvn_client/deprecated.c", 
   "(svn_client_log4): Followup to r35088: Initialize the revision ranges", 
   "array with size 1, since we know we're going to throw one range in it."
  ], 
  "revision_id": "875196"
 }
]