[
 {
  "author": "jdcryans", 
  "date": "2010-06-23T20:49:33.675754Z", 
  "msg": [
   "Scan doesn't recover from region server failure"
  ], 
  "revision_id": "957335"
 }, 
 {
  "author": "jdcryans", 
  "date": "2010-06-23T20:43:10.523634Z", 
  "msg": [
   "HBASE-2772  Scan doesn't recover from region server failure"
  ], 
  "revision_id": "957334"
 }, 
 {
  "author": "jdcryans", 
  "date": "2010-06-23T20:33:48.785848Z", 
  "msg": [
   "HBASE-2772  Scan doesn't recover from region server failure", 
   "HBASE-2775  Update of hadoop jar in HBASE-2771 broke TestMultiClusters"
  ], 
  "revision_id": "957333"
 }, 
 {
  "author": "pburba", 
  "date": "2010-06-23T20:32:51.571004Z", 
  "msg": [
   "On the 1.6.x-issue3646 branch: Merge r948512 from trunk.", 
   "* src-branch-1.6.x-4", 
   "Mergeinfo update.", 
   "* subversion/tests/cmdline/merge_tests.py", 
   "(cyclic_record_only_merge_creates_self_referential_mergeinfo): No", 
   "conflicts, but needed to adjust this new test to work on 1.6, i.e.", 
   "svntest.actions.run_and_verify_merge doesn't accept expected mergeinfo", 
   "and elision output."
  ], 
  "revision_id": "957332"
 }, 
 {
  "author": "todd", 
  "date": "2010-06-23T20:30:47.172158Z", 
  "msg": [
   "HBASE-2617. Load balancer falls into pathological state if one server under average - slop; endless churn", 
   "(Stack via Todd Lipcon)"
  ], 
  "revision_id": "957331"
 }
]